# Generated by Django 2.1.3 on 2018-11-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_cve_case_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve_case',
            name='url',
        ),
    ]
