# Generated by Django 2.1.3 on 2018-11-20 13:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve_case_tags',
            name='busi_orientation',
        ),
        migrations.RemoveField(
            model_name='cve_case_tags',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='cve_case_tags',
            name='media',
        ),
        migrations.RemoveField(
            model_name='cve_case_tags',
            name='product_style',
        ),
        migrations.RemoveField(
            model_name='cve_case_tags',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='cve_case_tags',
            name='year',
        ),
        migrations.AddField(
            model_name='cve_case_tags',
            name='container',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cve_case_tags',
            name='productCategory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cve_case_tags',
            name='scenes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cve_case_tags',
            name='style',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_case',
            name='colorArg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_case',
            name='cramArg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_case',
            name='jumpArg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_case',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cve_case',
            name='positionArg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_case',
            name='speedArg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='color',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='craMotion',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='during',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='position',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='speed',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cve_shot',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
