# Generated by Django 2.1.3 on 2018-11-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181120_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve_case',
            name='url',
            field=models.FileField(default='', upload_to='videos'),
        ),
    ]
